---
- name: Install requirements
  apt:
    name: 
      - openjdk-8-jdk-headless
      - apt-transport-https
      - ca-certificates
    state: present

- name: Import Jenkins apt key
  apt_key:
    url: https://pkg.jenkins.io/debian/jenkins.io.key
    state: present
  become: true

- name: Add Jenkins repository
  apt_repository: 
    repo: deb http://pkg.jenkins.io/debian-stable binary/
    state: present

- name: Install Jenkins
  apt: 
    name: jenkins
    update_cache: yes

- name: Change Jenkins port to 8000
  replace:
    path: /etc/default/jenkins
    regexp: 'HTTP_PORT=8080'
    replace: "HTTP_PORT=8000"
    backup: yes

- name: Restart jenkins
  ansible.builtin.service:
    name: jenkins
    state: restarted
