- name: Download kafka
  get_url:
    url: https://apache-mirror.rbc.ru/pub/apache/kafka/2.6.1/kafka_2.12-2.6.1.tgz
    dest: /tmp/kafka.tgz
    force_basic_auth: yes

- name: Extract
  ansible.builtin.unarchive:
    src: /tmp/kafka.tgz
    dest: /opt/
    remote_src: yes

- name: Copy zookeper unit
  ansible.builtin.copy:
    src: "zookeeper.service"
    dest: /etc/systemd/system/zookeeper.service

- name: Copy kafka unit
  ansible.builtin.copy:
    src: "kafka.service"
    dest: /etc/systemd/system/kafka.service
    
- name: Reload Units
  shell: systemctl daemon-reload 

- name: Start service zookeper
  ansible.builtin.service:
    name: zookeeper
    state: started
    enabled: yes 
    
- name: Start service kafka
  ansible.builtin.service:
    name: kafka
    state: started
    enabled: yes 

- name: Data upload
  shell:
    cmd: |
     sudo apt -y install git
     rm -rf $HOME/data
     git clone https://github.com/vadopolski/data-generator $HOME/data
     cd $HOME/data/src/main/resources/total
     /opt/kafka_2.12-2.6.1/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --topic billing --if-not-exists
     /opt/kafka_2.12-2.6.1/bin/kafka-configs.sh --bootstrap-server localhost:9092 --alter --topic billing --add-config retention.ms=31536000000
     cat billing_total.json | /opt/kafka_2.12-2.6.1/bin/kafka-console-producer.sh  --bootstrap-server localhost:9092 --topic billing
     /opt/kafka_2.12-2.6.1/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --topic issue --if-not-exists
     /opt/kafka_2.12-2.6.1/bin/kafka-configs.sh --bootstrap-server localhost:9092 --alter --topic issue --add-config retention.ms=31536000000
     cat issue_total.json | /opt/kafka_2.12-2.6.1/bin/kafka-console-producer.sh  --bootstrap-server localhost:9092 --topic issue
     /opt/kafka_2.12-2.6.1/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --topic payment --if-not-exists
     /opt/kafka_2.12-2.6.1/bin/kafka-configs.sh --bootstrap-server localhost:9092 --alter --topic payment --add-config retention.ms=31536000000
     cat payment_total.json | /opt/kafka_2.12-2.6.1/bin/kafka-console-producer.sh  --bootstrap-server localhost:9092 --topic payment
     /opt/kafka_2.12-2.6.1/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --topic traffic --if-not-exists
     /opt/kafka_2.12-2.6.1/bin/kafka-configs.sh --bootstrap-server localhost:9092 --alter --topic traffic --add-config retention.ms=31536000000
     cat traffic_total.json | /opt/kafka_2.12-2.6.1/bin/kafka-console-producer.sh  --bootstrap-server localhost:9092 --topic traffic


